### ISSUE TITLE
No way to send in "array" as data parameter

### ISSUE THREAD

**Issue by p4r4n0y1ng** [p4r4n0y1ng/pyfmg#10]
Starting my own issue - I recently found that there is no way to send in a request as an array to the data attribute - it's always Key Value. Thus, when doing things like ADDING an address object to an address group (or deleting one for that matter) without overwriting the whole object, you need to do something like this:

```
{
  "id": 1, 
  "method": "add", 
  "params": [
    {
      "data": [
        "membername1", 
        "membername2"
      ], 
      "url": "pm/config/adom/root/obj/firewall/addrgrp/test_addr_group/member"
    }
  ], 
  "session": "BLAH"
}
```

notice the data attribute is a list of things NOT a JSON object that's legal and then a list of things. In this case....there's no way to do this with the current code, without making some crazy mods. My petition is this:

I change the "common_datagram_params" function to handle a new keyword called "data". If this keyword is seen within the **kwargs pointer, then it will be used AS IS and other KV pairs in **kwargs will be thrown out - you can see how there won't be an "array" and then KV pairs within that same attribute.

Why would I use the keyword "data" - well, because that's the attribute name normally anyway, which means they probably will never have a keyword called "data" within the package so I think we're safe using it. The new code would look like:

```
@staticmethod
    def common_datagram_params(method_type, url, *args, **kwargs):
        params = [{"url": url}]
        if args:
            for arg in args:
                params[0].update(arg)
        if kwargs:
            keylist = list(kwargs)
            for k in keylist:
                kwargs[k.replace("__", "-")] = kwargs.pop(k)
            if method_type == "get" or method_type == "clone":
                params[0].update(kwargs)
            else:
                if kwargs.get("data", False):
                    params[0]["data"] = kwargs["data"]
                else:
                    params[0]["data"] = kwargs
        return params
```
and to call it you would do this:

```
fmg_instance.delete("pm/config/adom/root/obj/firewall/addrgrp/test_addr_group/member", data=["membername1", "membername2"])
```
Other options are available. If I hear nothing back in a day or so, I'll make this mod.

**Comment by mwclark4453** [comment]
I like that better than what I'm doing right now.  I created a data array variable basically data = ("data": [{member}, {member2}, ... {memberN}] and then passing it through the *args position for 'add' (the only command I've tried so far besides 'get').

Here is my code in case you are insterested
```
                        data = []
                        data = [{"data": [dstData["data"]]}]
                        print("Importing data into URL {}".format(urlDst))
                        logger.info("Importing data into URL %s", urlDst)
                        
                        logger.debug("using pyFMG to set %s", urlDst)
                        urlLock = "/dvmdb/adom/" + adomDst + "/workspace/lock"
                        urlcommit = "/dvmdb/adom/" + adomDst + "/workspace/commit"
                        urlUnlock = "/dvmdb/adom/" + adomDst + "/workspace/unlock"
                        rL = fmgDst.execute(urlLock)
                        responseDst = fmgDst.add(urlDst, *data)
                        resultCodeDst = responseDst[0]
                        resultCodeDstData = responseDst[1]
                        resultCode = "Failed"
                        if resultCodeDst == 0:
                            resultCode = "Success"
                            rU = fmgDst.execute(urlcommit)
                            rU = fmgDst.execute(urlUnlock)
                        else:
                            resultCode = resultCode + ": " + resultCodeDstData['status']['message']
                            rU = fmgDst.execute(urlUnlock)
```

Sorry I haven't changed it over to using your new locking schema.  I'm testing that either today or early next week.
