### ISSUE TITLE
Add the ability to send the 'verbose' setting in a request.

### ISSUE THREAD

**Issue by mwclark4453** [p4r4n0y1ng/pyfmg#11]
I posted a question on the Fortinet Developer Network today (https://fndn.fortinet.net/index.php?/forums/topic/1565-fmg-54-firewall-address-wildcard-fqdn-type-doesnt-match-documentation/) and got back a response that it is discouraged to use the integers in type settings but to use the strings instead.  This apparently is accomplished by adding a "verbose: 1" setting to the request.  That is being done in the FTNTLIB python script for JSON.  They use a self.verbose for the class and then add a function that sets it or clears it.  They also then add that to the request.

From FTNTLIB:
```pyrthon
class FortiManagerJSON (object):
    
    def __init__ (self):
        self._reqid = 1
        self._sid = None
        self._url = None
        self._ssl_verify = False
        self._debug = False
        self._bbcode = False
        self._ws_mode = False
        self._params = False
        self._skip = False
        self._verbose = False   
        self._root = False
        self._rootpath = None
        self._timeout = None

    def verbose (self, status):
        if status == 'on':
            self._verbose = 1
        if status == 'off':
            self._verbose = False

    def http_request (self,method,params):
        headers = { 'content-type' : 'application/json' }
        if self._params:
            params[0].update(self._params)
            self._params = False
        datagram = { 'id' : self._reqid, 
                     'session' : self._sid,
                     'method' : method,
                     'params' : params,
                    }
        if self._skip is not False:
            datagram['skip'] = int(self._skip)
        if self._verbose:
            datagram['verbose'] = int(self._verbose)
        if self._root:
            datagram['root'] = self._rootpath
            
        self.dprint('REQUEST:',datagram)

        try: 
            response = requests.post(
                                     self._url, 
                                     data=json.dumps(datagram), 
                                     headers=headers,
                                     verify=self._ssl_verify, 
                                     timeout=self._timeout
                                     )
            response = response.json()
        except requests.exceptions.ConnectionError as cerr:
            print ('Connection ERROR: ', cerr)
            return cerr
        except Exception as err:
            print ('ERROR: ', err)
            return err
        assert response['id'] == datagram['id']
        self.dprint('RESPONSE:',response)
        return self.response(response)
```

**Comment by p4r4n0y1ng** [comment]
Michael,
  You already have this capability - notice the *args solution in pyFMG

```
def common_datagram_params(method_type, url, *args, **kwargs):
        params = [{"url": url}]
        if args:
            for arg in args:
                params[0].update(arg)
```

So you have the ability to send in a list of things that fall into that level of the call.

So try something like:

fmginstance.add("/url/is/here", [{"verbose": 1}, ], keyword=value, keyword=value)

I'm doing this on the road so I'm doing it based on off my head type stuff, but please try. If it doesn't work, I'll send you a real one and how to do it. There are other things that need to be at this level of the call so I know I've added this. Try it and let me know please.

**Comment by mwclark4453** [comment]
That makes sense.  That's how I'm sending [data] instead of using the **kwargs.  I'll give it a try.

**Comment by p4r4n0y1ng** [comment]
Hmmmm.....doing a little testing and I added it for those cases when you needed something OUTSIDE the data dictionary - however, that's NOT going to do what YOU need......Also, I see that doesn't work for GET either.

Okay, let me think this one through - maybe a keyword value that targets this capability? My concern there is it gets mixed IN with the other keyword values that are then put in the data dict.

Some ideas? Maybe something obvious like 

```
external_kv_list=[{k:v}, {k2:v}, etc...]
```

This way there could be more and it would certainly not be something that would ever be seen within the FMG as a true Keyword Value option.  Remember this was written for Ansible so there was never a reason to do something like this, but....this is a good idea. Give me some thoughts on how to extend it.

Thanks.

**Comment by mwclark4453** [comment]
Being able to send any kv into the response would make it very extensible and basically future proof it without having to constantly come back and add yet another attribute to the class that needs to be set like the method being used in the fntnlib modules.  I wasn't even aware of the 'verbose' keyword until it was mentioned in the forums on fndn.fortinet.net because it's not in the HTML API documentation.

**Comment by jamesdreid** [comment]
#16 There is now a verbose option available to the GET method in the base branch so this can likely be closed.
