### ISSUE TITLE
requests.packages.urllib3 AttributeError: 'module' object has no attribute 'urllib3'

### ISSUE THREAD

**Issue by pacrutchet** [p4r4n0y1ng/pyfmg#17]
Hello,

When using requests version 2.23.0, there is no module urllib3 in requests.packages.

So the \_\_init\_\_() function crash on \:

```
if disable_request_warnings:
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
```

It would probably work better to call directly urllib3.disable_warnings()

**Comment by p4r4n0y1ng** [comment]
I am using 2.23 and it's not crashing. Not saying you're wrong, but I'm not running into this error and I'm using this version.

**Comment by pacrutchet** [comment]
Indeed, bad package centos, sorry for that!
