### ISSUE TITLE
Bug: version 0.8.6.0 login returns -1 after successfull login with user & passwd

### ISSUE THREAD

**Issue by broterki** [p4r4n0y1ng/pyfmg#28]
Hello,

I discovered an issue with version 0.8.6.0. In my script, I use the return value of login() to detect if the login was successful. With version 0.8.6.0, login() returns -1 if my script logs in successfully to the FortiManager using a username and password. Version 0.8.5.5 does not show this behavior and returns 0.

Mario

**Comment by tigeb** [comment]
Same error here, and this is coming from a typing error with word "connected" in fortimgr.__str__()

    def __str__(self):
        if self.sid is not None:
            return "FortiManager instance connnected to {host}.".format(host=self._host)       <-----------
        return "FortiManager object with no valid connection to a FortiManager appliance."

**Comment by p4r4n0y1ng** [comment]
Ouch....  facepalm. Thanks @tigeb and I'm fixing that now @broterki. Please let me know if 8.6.1 solves this for you!

**Comment by broterki** [comment]
I apologize for the late response; 0.8.6.1 fixes the issue for me. Thank you very much!
