### ISSUE TITLE
Request "data" should be a list of objects and not just an object

### ISSUE THREAD

**Issue by mwclark4453** [p4r4n0y1ng/pyfmg#3]
The API documentation shows the following format for the "SET" method:
{
   "method": "set",
   "params": [ {
      "url": "...",
      "data": [ { ... } ]
   } ],
   "session": "...",
   "id": 1
}

Every URL I've worked with so far apparently doesn't care if "data": {...} versus "data": [{...}] except for one.  When trying to add a policy to an ADOM via the URL /pm/pkg/adom/adomName, the API returns an error.  When I changed fortimgr.py to send a list instead, it worked.  The firewall address URL and addrGroup URL didn't seem to mind the change.

Here is the change I made:
def common_datagram_params(url, **kwargs):
        params = [{'url': url}]
        if kwargs:
            data = kwargs
            # API docs say this needs to be a list. Make it one.
            dataList = []
            dataList.append(data)
            params[0]['data'] = dataList
        return params

Once my FNDN access goes through, I plan on posting the question why this one URL seems to care.  NOTE:  This is on a FMG 5.4.

**Comment by p4r4n0y1ng** [comment]
Yes, there is this problem every now and then. What I did initially when I found this about a year ago, I had the code look for a negative response and then if it got the error it tried with the list...basically if at first it didn't succeed, it tried again. Possibly I'll incorporate that into pyfmg!

**Comment by mwclark4453** [comment]
That would be excellent.  I really like the context approach better than the FTNTLIB one on FNDN.

**Comment by mwclark4453** [comment]
Your latest version is not displaying this error anymore.  This issue can be closed.  Thanks for all your hard work on all the issues.
