### ISSUE TITLE
Firewall Policy error not returning just "status" but also including a "data" result

### ISSUE THREAD

**Issue by mwclark4453** [p4r4n0y1ng/pyfmg#9]
When running with the new pyFMG code, I got back responses when trying to add new policies to an ADOM.  Below is the result code when running with debug messages on:
```
RESPONSE:
{
  "id": 335,
  "result": [
    {
      "data": {
        "policyid": 1
      },
      "status": {
        "code": -10131,
        "message": "datasrc invalid. object: firewall policy dstintf 1. detail: agg-1-vlan-4. solution: data not exist"
      },
      "url": "/pm/config/adom/sod-001/pkg/root/firewall/policy"
    }
  ]
}
```
This causes the def _handle_response to send the "data" through and not the error message like every other request.  I've patched my fortimgr.py file to always check for a 0 result and just send the result back if it's anything other than 0.  Below is the new _handle_response.  I've tested this on a 5.6 FMG when moving and ADOM from a 5.4 to a 5.4 ADOM on the 5.6 FMG.  I don't know if you want to include this in future updates or not:
```python
    def _handle_response(self, response):
        self._set_sid(response)
        if type(response["result"]) is list:
            result = response["result"][0]
        else:
            result = response["result"]
        resultCode = 0
        if "status" in result:
            resultCode = result["status"]["code"]
        if resultCode == 0:
            if "data" in result:
                return result["status"]["code"], result["data"]
            else:
                return result["status"]["code"], result
        else:
            return result["status"]["code"], result
```

**Comment by p4r4n0y1ng** [comment]
True - the more I look at this, the more I need to make some better changes anyway to that function. More to follow - will have it fixed up better soon.

**Comment by p4r4n0y1ng** [comment]
With all the new updates to pyFMG - are you still running into this issue?
